### ISSUE TITLE
Add parameterisation to named queries

### ISSUE THREAD

**Issue by thislarz** [WolfgangFahl/pyLoDStorage#113]
Independent of the target Language SQL or SparQL named queries should allow for named parameters. Parameters should be specified as a dict useing native python datatypes.

Example:
```python



```

Follow up Problems:
- Injections attacts should be avoided.
- Update Documentation to demonstrate use.

**Comment by tholzheim** [comment]
https://github.com/WolfgangFahl/pyLoDStorage/blob/61ce933df32fcc0cf853b2877eb8d8c7424c0882/tests/test_queries.py#L29-L35

**Comment by tholzheim** [comment]
SPARQL Injections attacts: see https://stackoverflow.com/questions/29601839/standard-regex-to-prevent-sparql-injection

**Comment by WolfgangFahl** [comment]
see #114

**Comment by WolfgangFahl** [comment]
see https://github.com/w3c/sparql-dev/issues/57
