### ISSUE TITLE
sqlite3 default adapter and converter deprecated as of python 3.12

### ISSUE THREAD

**Issue by tholzheim** [WolfgangFahl/pyLoDStorage#127]
The default adapters and converters are deprecated as of Python 3.12 see https://docs.python.org/3/library/sqlite3.html#default-adapters-and-converters-deprecated

The suggested alternative adapters and converters (https://docs.python.org/3/library/sqlite3.html#sqlite3-adapter-converter-recipes) were added with commit 66a90ddf94d6ae7436914de330d000a63be75f41

The tests [testSqlite3.py](https://github.com/WolfgangFahl/pyLoDStorage/blob/master/tests/testSqlite3.py) include the needed date, timestamp and boolean data type fields and the test cases execute successfully see https://github.com/WolfgangFahl/pyLoDStorage/actions/runs/9042260772

The replacements for the default adapters and converters should exactly replicate the behavior to be able to reuse existing databases.

@WolfgangFahl reported a compatibility issue of the suggested [adapters and converters](https://docs.python.org/3/library/sqlite3.html#sqlite3-adapter-converter-recipes) with databases created with the default adapters

**Comment by WolfgangFahl** [comment]
see also #51

**Comment by WolfgangFahl** [comment]
```  File "..../pyLoDStorage/lodstorage/sql.py", line 675, in convert_timestamp
    return datetime.datetime.fromtimestamp(float(val)/10**6)
ValueError: could not convert string to float: b'1995-04-07 00:00:00'
```

**Comment by tholzheim** [comment]
Check https://github.com/WolfgangFahl/pyLoDStorage/blob/20ac1155a5a17efaa338a2755472a28b9b46a4c2/lodstorage/sql.py#L667-L668C35
