### ISSUE TITLE
Functionality to convert between LoD and CSV

### ISSUE THREAD

**Issue by tholzheim** [WolfgangFahl/pyLoDStorage#29]
Example:
CSV input:
```csv
pageTitle,name,label
page_1,Test Page 1,1
page_2,Test Page 2,2
```
LoD output:
```
[
  {"pageTitle": "page_1", "name": "Test Page 1", "label": "1"},
  {"pageTitle": "page_2", "name": "Test Page 2", "label": "2"}
]
```
Currently unsure where the type conversion should happen.
The LoD can be converted to JSONAble so the Type conversion could be done there.

**Comment by tholzheim** [comment]
https://github.com/WolfgangFahl/pyLoDStorage/commit/be7a85c6ecd24e2b02ed142ed5803c7db67396e4

**Comment by WolfgangFahl** [comment]
see https://stackoverflow.com/a/67289224/1497139 and the added type handling test with the standard Royals example
